### ISSUE TITLE
Black tiles instead of icons.

### ISSUE THREAD

**Issue by baza3000** [P3N-101/icon-menu-builder#2]
Instead of seeing any icons, i just get black tiles.
If i open the Microsoft Graphics category, i get some icons but then nothing shows on the Selected Icon section of the app.
The app seems to work fine in Edit/Play mode apart from being able to scroll the left hand Nav menu to see/access the bottom categories.

![IconMenu2](https://user-images.githubusercontent.com/39268515/117635364-a442d500-b177-11eb-9a0c-14bf02800bf6.JPG)
![IconMenu](https://user-images.githubusercontent.com/39268515/117635368-a4db6b80-b177-11eb-8343-4f14b5814c01.JPG)

**Comment by P3N-101** [comment]
Hey @baza3000, I have run through the installation on 2 tenants in different environments and haven't been able to replicate this..
From the bottom screen the color pickers seem to be missing, these controls the color on the screen and if not there then Black is the default for no values or failures.

When you open in edit mode are the pickers there?  Try reinstalling the ColorPicker_managed.zip solution.

**Comment by baza3000** [comment]
Ah yes, reinstalling the ColorPicker_managed.zip has actually resolved the issue.
Thank you very much!

**Comment by P3N-101** [comment]
I actually manged to replicate this on a tenant today.... I reinstalled the color picker, then I removed the Screen1 from the app... it was just a test screen and then re published it and it worked.... Happy you got it working... 

Next version I am going to change the icon menus to a 2 level menu so you will get to see all the icon packs on smaller screens.... I work on a 2K screen so thats what I design my tools for...

**Comment by baza3000** [comment]
Ah no worries. If i zoom my browser out to 80%, i can access all the icons. 
Next version sounds great, can't wait!
