### ISSUE TITLE
Unable to Install PPIconMenuBuilder_1_0_0_17_managed Solution

### ISSUE THREAD

**Issue by LinnZawWin** [P3N-101/icon-menu-builder#3]
I am getting the following error during the import even if I select the SharePoint list environment or not.

![image](https://user-images.githubusercontent.com/14156926/128647375-1771186c-9355-404c-82af-e817a1be8a36.png)

Unprocessed files found: /environmentvariabledefinitions/new_shared_sharepointonline_50779c7c9339487aa389e42a15cd43cf/environmentvariablevalues.json, /environmentvariabledefinitions/new_shared_sharepointonline_6bde46b23fc0440cb95fb23af51d29ff/environmentvariablevalues.json, /environmentvariabledefinitions/new_shared_sharepointonline_b3d817f9ce924478bda4b33556b09f5e/environmentvariablevalues.json

![image](https://user-images.githubusercontent.com/14156926/128647288-c1163e31-d95a-4508-bbe9-67b9a918472a.png)

**Comment by P3N-101** [comment]
Not seen this before...will do some investigations. and let you know

**Comment by LinnZawWin** [comment]
I noticed that the x3 Environment Variables at the bottom of my screenshot are not there in the [Installation Guide](https://pensplace.github.io/icon-menu-builder-docs/installation/). I am not sure if something has changed from Microsoft which is causing this issue.

My environment is in Oceania region https://*****.crm6.dynamics.com/ if that helps with your investigation.

For now, I have just installed the [.msapp](https://github.com/P3N-101/icon-menu-builder/blob/main/solution/Icon%20Menu%20Builder.msapp) and run it in the Power Apps studio. Once again, thank you for this amazing app. 

![image](https://user-images.githubusercontent.com/14156926/129263909-a876cd06-460a-4523-a1b4-c26f5a8bc665.png)
