### ISSUE TITLE
Installation of Menu Builder v2 RC1 fails

### ISSUE THREAD

**Issue by txh57** [P3N-101/icon-menu-builder#4]
During import of solution **PPIconMenuBuilderv2_2_0_0_3_managed.zip** I'm receiving the following error message:

![PPMenuBuilder_error](https://user-images.githubusercontent.com/25150539/148682337-d217ed45-7539-48b3-b1e4-ac3abf4fdab1.png)

**Comment by P3N-101** [comment]
Please make sure the Upload and Download components are installed into the environment before importing... I was having this issue as the component did not exit in the environment.

**Comment by txh57** [comment]
All of the 4 solutions were already installed before I tried to import the Menu Builder v2 solution.
Solution PP-Icon Menu Builder 1.0.0.12 was already installed in this sandbox environment.

These are the steps I tried next:
1.  Delete the 4 helper solutions



2. Import all 4 solutions again
![image](https://user-images.githubusercontent.com/25150539/148696186-5552d33f-e126-46dd-8fa9-ece8f4fb46b6.png)
3. Import Menu Builder v2
![image](https://user-images.githubusercontent.com/25150539/148696406-ac3dc0ac-8b33-4651-a404-f0343de67f13.png)
4. Deleted PP-Icon Menu Builder 1.0.0.12 solution
5. Import Menu Builder v2
![image](https://user-images.githubusercontent.com/25150539/148696262-846e1d0a-3ab7-40e7-8c0e-ffa59ba414cb.png)

**Comment by txh57** [comment]
Addendum to the last comment:

I also tried to import the Menu Builder v2 into a completely new and empty trial environment - with the same results.

**Comment by P3N-101** [comment]
Thats for the info, I am working on repackaging it with all the components included in a solution file, the current issue is being casused by the download control...

**Comment by gruering** [comment]
The reason is because the solution exceeds the max size of 29MB. Please repackage the solution to a supported limit.
Reference: https://docs.microsoft.com/en-us/power-platform-release-plan/2019wave2/microsoft-powerapps/new-solution-components-get-full-support#feature-details

**Comment by P3N-101** [comment]
I was actually down to one of the Code components and the publishers being mismatched.  I have repackaged the components and created a single solution file.  This should import without issue.. Please let me know if you have trouble.
