### ISSUE TITLE
v2-rc21 - SharePoint Setup flow fails

### ISSUE THREAD

**Issue by txh57** [P3N-101/icon-menu-builder#5]
The import of the solution works now - great job.

Two things are not yet running smoothly:
1. During the import of the current solution, the import process did not ask for the environment variable for the SharePoint site.
2. The flow for the SharePoint setup fails because it is not part of a solution - and cannot be added to one. Environment Variables can be used for flows only in solutions.

**Comment by P3N-101** [comment]
Happy to say finally got around to fixing the solution, flow is now included,.. Get the latest [here](https://github.com/P3N-101/icon-menu-builder/releases/tag/v2.0.0.11)
